#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"
npm run lint:fix || exit 1
npm run lint:style:fix || exit 1
npm run format || exit 1

#npm run lint || exit 1    
#npm run lint:style || exit 1
#npm run format:check || exit 1